Algoritmo "Operadores Relacionais"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/10/2021
Var
// Seção de Declarações das variáveis 
   nota1, nota2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota1 <- 25
   nota2 <- 50

   se(nota1 > nota2) entao
        escreval("A nota 1 é maior! ")
   senão
        escreval("A nota 1 é menor")
   fimse
Fimalgoritmo